Got SillyError with message: Some error
Finally
